site_name: VHC-TestDataScience-2

nav:
  - Home: index.md
  - Data Cleaning: data-cleaning.md
  - Sesonality: sesonality.md
  - Data Exploration: data-exploration.md
  - Pre-processing: pre-processing.md
  - LSTM Modeling: modeling.md
  - Forecasting: forecasting.md
  - Results: results.md
